services:
  to_do_list_app:
    container_name: to_do_list_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    env_file:
      - envs/.env