services:
  to_do_list_app:
    container_name: to_do_list_app
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: True
    tty: True
    restart: always
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    env_file:
      - envs/.env
