version: "3.8"
services:
  to_do_list_app:
    container_name: to_do_list_app
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    env_file:
      - envs/.env
    command: ["/bin/bash", "-c", "python manage.py runserver 0.0.0.0:8002"]