# Generated by Django 4.2.3 on 2023-07-14 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_criacao', models.DateField(auto_now_add=True, verbose_name='Data de criação')),
                ('data_atualizacao', models.DateField(auto_now=True, verbose_name='Data de atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('status', models.CharField(choices=[(1, 'Concluido'), (2, 'Em andamento'), (3, 'Bloqueado'), (4, 'Finalizado')], max_length=15, verbose_name='Status')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
