# Generated by Django 4.2.3 on 2023-07-14 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.CharField(choices=[(1, 'Concluido'), (2, 'À fazer'), (3, 'Em andamento'), (4, 'Bloqueado'), (5, 'Finalizado')], max_length=15, verbose_name='Status'),
        ),
    ]
