# Generated by Django 4.2.3 on 2023-07-16 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='username',
            field=models.CharField(default='user_defult_value', max_length=255, verbose_name='Username'),
        ),
    ]
