# Generated by Django 4.2.3 on 2023-07-14 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_todolist_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.CharField(choices=[('Concluido', 'Concluido'), ('À fazer', 'À fazer'), ('Em andamento', 'Em andamento'), ('Bloqueado', 'Bloqueado'), ('Finalizado', 'Finalizado')], max_length=15, verbose_name='Status'),
        ),
    ]
