# Generated by Django 5.0.7 on 2024-08-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customusuario_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='status',
            field=models.CharField(choices=[('Concluido', 'Concluido'), ('À fazer', 'À fazer'), ('Em andamento', 'Em andamento'), ('Pausado', 'Pausado'), ('Finalizado', 'Finalizado')], max_length=15, verbose_name='Status'),
        ),
    ]
