name: To Do List CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Criar e ativar virtualenv
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Instalar dependências
        run: pip install -r requirements.txt
      
      - name: Rodar migrações
        run: |
          python manage.py makemigrations
          python manage.py migrate

      - name: Rodar testes
        run: python manage.py test

      - name: Configurar variáveis de ambiente
        run: |
          echo "DEBUG=False" >> .env
          echo "SECRET_KEY=supersecreta" >> .env
          echo "ALLOWED_HOSTS=127.0.0.1" >> .env

      - name: Baixar e Instalar Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Adicionar Docker Compose ao PATH
        run: |
          export PATH=$PATH:/usr/local/bin

      - name: Subir containers do Docker
        run: docker-compose up -d --build